import { receiveCatalog } from "../catalog/service.js";
import { z } from "zod";
import { createHmac, timingSafeEqual } from "node:crypto";
import { jwtSecret } from "../../config.js";
import { systemCtx, withDb } from "../../lib/db.js";
import { ApiError } from "../../lib/errors.js";
import { authorizeNativeRead, executeNativeAction, type NativeScope, type NativePermission } from "./actions.js";
import * as approvalRepo from "./approval-repo.js";
import { quoteHash, type QuoteOptions } from "./quote.js";
import { confirmDraft } from "./service.js";
import { modifyOrder, cancelOrder } from "./orders.js";
import { modifyOrderSchema, cancelOrderSchema } from "./schemas.js";

const permissions: Record<string, NativePermission> = { recibir_pedido_catalogo: "create_orders", confirmar_pedido: "create_orders", modificar_pedido: "modify_orders", cancelar_pedido: "cancel_orders" };
function perform(scope: NativeScope, name: string, args: unknown, options: QuoteOptions) {
  if (name === "recibir_pedido_catalogo") {
    const input = z.object({ sourceMessageId: z.string().uuid() }).strict().parse(args);
    return receiveCatalog({ businessId: scope.businessId, conversationId: scope.conversationId, messageId: input.sourceMessageId }, options);
  }
  if (name === "confirmar_pedido") return confirmDraft(scope.businessId, scope.conversationId, options);
  if (name === "modificar_pedido") return modifyOrder(modifyOrderSchema.parse({ ...args as object, ...scope }), options);
  if (name === "cancelar_pedido") return cancelOrder(cancelOrderSchema.parse({ ...args as object, ...scope }), options);
  throw new ApiError("VALIDATION_ERROR", "Acción inválida.");
}
const sign = (value: string) => createHmac("sha256", jwtSecret).update(`agent-approval:${value}`).digest("hex").slice(0, 32);
export function approvalButtons(id: string) {
  return ([['yes', 'Confirmar'], ['no', 'No confirmar']] as const).map(([choice, title]) => {
    const value = `${id}:${choice}`;
    return { type: "postback", title, payload: `toki:${value}:${sign(value)}` };
  });
}
function parseButton(value: string) {
  const match = /^toki:([0-9a-f-]{36}):(yes|no):([0-9a-f]{32})$/.exec(value);
  if (!match) return null;
  const signed = `${match[1]}:${match[2]}`;
  if (!timingSafeEqual(Buffer.from(sign(signed)), Buffer.from(match[3]!))) return null;
  return { id: match[1]!, approved: match[2] === "yes" };
}

export async function requestApproval(scope: NativeScope, toolName: string, args: unknown) {
  await authorizeNativeRead(scope, permissions[toolName]);
  const result = await perform(scope, toolName, args, { quoteOnly: true });
  if (!("quote" in result) || !result.quote) return result;
  const quote = result.quote;
  const approval = await withDb(systemCtx, tx => approvalRepo.createApproval(tx, scope, toolName, args, quote));
  return { ok: true, pendingApproval: true, approvalId: approval.id, quote, instruction: "Todavía no se ejecutó. Toki adjuntará el resumen exacto y los botones. Pedí al cliente que confirme con el botón." };
}

/** Only a signed interactive tap from this conversation can consume a proposal. Text is never authorization. */
export async function consumeApproval(scope: NativeScope, interactiveId?: string) {
  const choice = interactiveId ? parseButton(interactiveId) : null;
  const pending = await withDb(systemCtx, tx => approvalRepo.claimApproval(tx, scope, choice));
  if (!pending) return interactiveId ? { ok: false, error: "La confirmación venció o no corresponde a esta conversación. Hay que preparar un nuevo resumen." } : null;
  if (!pending.approved) return { ok: true, denied: true, instruction: "El cliente rechazó la acción. No la ejecutes ni la vuelvas a solicitar salvo que pida un cambio nuevo." };
  try {
    const a = pending.approval;
    const result = await executeNativeAction({ scope, permission: permissions[a.toolName]!, toolName: a.toolName,
      args: { approvalId: a.id }, execute: () => perform(scope, a.toolName, a.args, { expectedQuote: quoteHash(a.quote) }) });
    await withDb(systemCtx, tx => approvalRepo.finishApproval(tx, a.id, "approved"));
    return { toolName: a.toolName, result };
  } catch (error) {
    await withDb(systemCtx, tx => approvalRepo.finishApproval(tx, pending.approval.id, "failed"));
    throw error;
  }
}

/** Transactional content only: conversation prose remains generated by the model. */
export function approvalSummary(value: unknown): string {
  const q = value as Record<string, unknown>;
  const currency = (v: unknown) => Number(v ?? 0).toLocaleString("es-AR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  if (q.action === "cancelar_pedido") return `Cancelar pedido ${q.orderCode}\nTotal del pedido: $ ${currency(q.total)}\n${q.paymentStatus === "paid" ? "Si corresponde un reembolso, el equipo lo gestionará; no se devuelve dinero automáticamente." : ""}`.trim();
  const items = [...(Array.isArray(q.items) ? q.items : []), ...(Array.isArray(q.added) ? q.added : [])] as Record<string, unknown>[];
  const lines = items.map(i => `${i.quantity} × ${i.productName ?? i.name}${i.notes ? ` — ${i.notes}` : ""}${Array.isArray(i.options) && i.options.length ? ` (${i.options.map((o: Record<string, unknown>) => o.valueName).join(", ")})` : ""}`);
  return [q.action === "modificar_pedido" ? `Modificar pedido ${q.orderCode}` : "Confirmar pedido", ...lines,
    q.customerName ? `A nombre de: ${q.customerName}` : "",
    q.orderType === "delivery" ? `Envío a: ${q.deliveryAddress ?? q.address}` : "Retiro en el local",
    `Pago: ${q.paymentMethod === "cash" ? "efectivo" : q.paymentMethod === "transfer" ? "transferencia" : q.paymentMethod}`,
    q.couponCode ? `Cupón: ${q.couponCode} · Descuento: $ ${currency(q.discountTotal)}` : "",
    Number(q.deliveryFee) ? `Envío: $ ${currency(q.deliveryFee)}` : "",
    q.notes ? `Notas: ${q.notes}` : "",
    `Total: $ ${currency(q.total)}`, "La confirmación vence en 10 minutos."].filter(Boolean).join("\n");
}
